name: CI - Test & Qodana Scan

on:
  push:
    branches-ignore:
      - master
  pull_request: {}


jobs:
  build_and_scan:
    name: Build, Test, and Static Analysis
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      pull-requests: read

    steps:
      # 1️ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️ Set up JDK 25 (Temurin)
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      # 3️ Test with Maven
      - name: Test Maven project
        run: mvn clean verify

      # 4️ Run Qodana Static Code Analysis
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: true
          args: --apply-fixes
          commit-message: "Qodana code push report"
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      # 5️ Upload Maven test reports
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: target/surefire-reports
