name: Qodana
on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --apply-fixes
          pr-mode: true
          push-fixes: pull-request
          commit-message: "Qodana Auto-fix applied"
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
