name: Qodana + Build + Docker

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_scan:
    name: Build, Scan, and Dockerize
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      checks: write
      packages: write

    steps:
      # 1️ Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️ Set up JDK 25 (Temurin)
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      # 3️ Build with Maven
      - name: Build Maven project
        run: mvn clean package

      # 4️ Run Qodana Static Analysis
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --apply-fixes
          pr-mode: true
          push-fixes: pull-request
          commit-message: "Qodana Pull request report"
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      # 5️ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 6 Get Maven Project Version
      - name: Read project version from pom.xml
        id: project_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      # 7 Build Docker Image
      - name: Build Docker image
        run: |
          echo "Building image for version: ${{ steps.project_version.outputs.version }}"
          docker build \
            --build-arg argBasedVersion=${{ steps.project_version.outputs.version }} \
            --build-arg argBasedPassword="default" \
            --build-arg spring_profile="dev" \
            -t wrongsecrets-app:${{ steps.project_version.outputs.version }} \
            -t wrongsecrets-app:latest .

      # 8 Save Docker image as artifact
      - name: Save image as artifact
        run: docker save wrongsecrets-app:latest -o wrongsecrets-app.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: wrongsecrets-docker-image
          path: wrongsecrets-app.tar
